name: Build and Deploy to EKS

# Déclenchement du pipeline sur trigger "Push"
on:
  push:
    branches: ['master']
  #pull_request:
  #  branches: ['master']

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:

        # Checkout du code
      - name: Checkout code
        uses: actions/checkout@v3

        # installation client kubebernetes pour le déploiement
      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.24.0'
        id: install


